# Generated by Django 2.1.1 on 2018-09-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfund',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Mutualfund',
        ),
    ]
